//<![CDATA[
function relatedPostsWidget(g){(function(b){var a={blogURL:"",maxposts:3,maxTags:10,maxpostsPerTag:10,containerSelector:"",tags:null,loadingText:"",loadingClass:"",relevantTip:"",rlt_summary:70,relatedTitle:"Related Posts",rlpBlank:"http://4.bp.blogspot.com/-44trijSlV2Y/UgU0J6RU87I/AAAAAAAAASU/Nppm2hzUboU/s1600/no_image.jpg",rlt_thumb:190,postScoreClass:"",onLoad:!1},a=b.extend({},a,g),c=0,k=null,l=null;a.containerSelector||(document.write('<div id="relatedposts"></div>'),a.containerSelector=".relatedposts");
var n=function(q,g){c++;if(q.feed.entry)for(var r=0;r<q.feed.entry.length;r++){for(var d=q.feed.entry[r],f="",e=0;e<d.link.length;e++)if("alternate"==d.link[e].rel){f=d.link[e].href;break}e="content"in d?d.content.$t:"summary"in d?d.summary.$t:"";e=e.replace(/<\S[^>]*>/g,"");e.length>a.rlt_summary&&(e=e.substring(0,a.rlt_summary)+"...");var m=d.title.$t,n="media$thumbnail"in d?d.media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/s"+a.rlt_thumb+""):a.rlpBlank;if(location.href.toLowerCase()!=f.toLowerCase())a:{for(var d=
f,h=m,p=e,e=b("li",l),f=0;f<e.length;f++){var s=b("a",e.eq(f)),m=t(s);if(s.attr("href")==d){d=s;h=++m;d.attr("score",h);a.relevantTip&&d.attr("title",a.relevantTip.replace("d",h));a.postScoreClass&&d.attr("class",a.postScoreClass+h);for(d=f-1;0<=d;d--)if(h=b("a",e.eq(d)),t(h)>m){1<f-d&&e.eq(d).after(e.eq(f));break a}0<f&&e.eq(0).before(e.eq(f));break a}}l.append('<li><a class="jdlunya" href="'+d+'" title="'+(a.relevantTip?a.relevantTip.replace("d",1):"")+'"><span class="gmbrrltd"><img width="'+a.rlt_thumb+
'" height="'+a.rlt_thumb+'" alt="'+h+'" src="'+n+'"/></span><strong>'+h+"</strong></a><p>"+p+"</p></li>")}}c>=a.tags.length&&(l.attr("class",""),b("#related-posts-loadingtext",k).remove(),0<a.maxposts&&b("li:gt("+(a.maxposts-1)+")",l).remove())},t=function(a){a=parseInt(a.attr("score"));return 0<a?a:1},p=function(){if(".relatedposts"!=a.containerSelector){var c=b(a.containerSelector);if(1!=c.length)return;k=b('<div id="relatedposts"></div>').appendTo(c)}else k=b(a.containerSelector);a.tags||(a.tags=
[],b('a[rel="tag"]:lt('+a.maxTags+")").each(function(){var c=b.trim(b(this).text().replace(/\n/g,""));-1==b.inArray(c,a.tags)&&(a.tags[a.tags.length]=c)}));if(0!=a.tags.length||a.recentTitle)if(0==a.tags.length?b('<div class="relhead"><h4><span>'+a.recentTitle+"</span></h4></div>").appendTo(k):a.relatedTitle&&b('<div class="relhead"><h4><span>'+a.relatedTitle+"</span></h4></div>").appendTo(k),a.loadingText&&b('<div id="related-posts-loadingtext">'+a.loadingText+"</div>").appendTo(k),l=b("<ul "+(a.loadingClass?
'class="'+a.loadingClass+'"':"")+"></ul>").appendTo(k),0==a.tags.length)b.ajax({url:a.blogURL+"/feeds/posts/summary/",data:{"max-results":a.maxpostsPerTag,alt:"json-in-script"},success:n,dataType:"jsonp",cache:!0});else for(c=0;c<a.tags.length;c++)b.ajax({url:a.blogURL+"/feeds/posts/summary/",data:{category:a.tags[c],"max-results":a.maxpostsPerTag,alt:"json-in-script"},success:n,dataType:"jsonp",cache:!0})};a.onLoad?b(window).load(p):b(document).ready(p)})(jQuery)}
function createCookie(g,b,a){if(a){var c=new Date;c.setTime(c.getTime()+864E5*a);a="; expires="+c.toGMTString()}else a="";document.cookie=g+"="+b+a+"; path=/"}function readCookie(g){g+="=";for(var b=document.cookie.split(";"),a=0;a<b.length;a++){for(var c=b[a];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(g))return c.substring(g.length,c.length)}return null}function eraseCookie(g){createCookie(g,"",-1)};
//]]>
