//<![CDATA[
(function(a){function s(){var b=l.scrollLeft(),c=l.width();a([d,p]).css("left",b+c/2);C&&a(m).css({left:b,top:l.scrollTop(),width:c,height:l.height()})}function D(b){b?a("object").add(E?"select":"embed").each(function(a,b){x[a]=[b,b.style.visibility];b.style.visibility="hidden"}):(a.each(x,function(a,b){b[0].style.visibility=b[1]}),x=[]);b=b?"bind":"unbind";l[b]("scroll resize",s);a(document)[b]("keydown",M)}function M(b){b=b.which;var d=a.inArray;return 0<=d(b,c.closeKeys)?y():0<=d(b,c.nextKeys)?
F():0<=d(b,c.previousKeys)?G():null}function G(){return z(q)}function F(){return z(r)}function z(a){0<=a&&(g=a,t=h[g][0],q=(g||(c.loop?h.length:0))-1,r=(g+1)%h.length||(c.loop?0:-1),H(),d.className="lbLoading",f=new Image,f.onload=N,f.src=t);return!1}function N(){d.className="";a(n).css({backgroundImage:"url("+t+")",visibility:"hidden",display:""});a(A).width(f.width);a([A,u,v]).height(f.height);a(I).html(h[g][1]||"");a(J).html((1<h.length&&c.counterText||"").replace(/{x}/,g+1).replace(/{y}/,h.length));
0<=q&&(K.src=h[q][0]);0<=r&&(L.src=h[r][0]);e=n.offsetWidth;k=n.offsetHeight;var b=Math.max(0,B-k/2);d.offsetHeight!=k&&a(d).animate({height:k,top:b},c.resizeDuration,c.resizeEasing);d.offsetWidth!=e&&a(d).animate({width:e,marginLeft:-e/2},c.resizeDuration,c.resizeEasing);a(d).queue(function(){a(p).css({width:e,top:b+k,marginLeft:-e/2,visibility:"hidden",display:""});a(n).css({display:"none",visibility:"",opacity:""}).fadeIn(c.imageFadeDuration,O)})}function O(){0<=q&&a(u).show();0<=r&&a(v).show();
a(w).css("marginTop",-w.offsetHeight).animate({marginTop:0},c.captionAnimationDuration);p.style.visibility=""}function H(){f.onload=null;f.src=K.src=L.src=t;a([d,n,w]).stop(!0);a([u,v,n,p]).hide()}function y(){0<=g&&(H(),g=q=r=-1,a(d).hide(),a(m).stop().fadeOut(c.overlayFadeDuration,D));return!1}var l=a(window),c,h,g=-1,t,q,r,C,B,e,k,E=!window.XMLHttpRequest,x=[],f={},K=new Image,L=new Image,m,d,n,A,u,v,p,w,I,J;a(function(){a("body").append(a([m=a('<div id="lbOverlay" />').click(y)[0],d=a('<div id="lbCenter" />')[0],
p=a('<div id="lbBottomContainer" />')[0]]).css("display","none"));n=a('<div id="lbImage" />').appendTo(d).append(A=a('<div style="position: relative;" />').append([u=a('<a id="lbPrevLink" href="#" />').click(G)[0],v=a('<a id="lbNextLink" href="#" />').click(F)[0]])[0])[0];w=a('<div id="lbBottom" />').appendTo(p).append([a('<a id="lbCloseLink" href="#" />').click(y)[0],I=a('<div id="lbCaption" />')[0],J=a('<div id="lbNumber" />')[0],a('<div style="clear: both;" />')[0]])[0]});a.slimbox=function(b,
g,f){c=a.extend({loop:!1,overlayOpacity:.8,overlayFadeDuration:400,resizeDuration:400,resizeEasing:"swing",initialWidth:250,initialHeight:250,imageFadeDuration:400,captionAnimationDuration:400,counterText:"Image {x} of {y}",closeKeys:[27,88,67],previousKeys:[37,80],nextKeys:[39,78]},f);"string"==typeof b&&(b=[[b,g]],g=0);B=l.scrollTop()+l.height()/2;e=c.initialWidth;k=c.initialHeight;a(d).css({top:Math.max(0,B-k/2),width:e,height:k,marginLeft:-e/2}).show();if(C=E||m.currentStyle&&"fixed"!=m.currentStyle.position)m.style.position=
"absolute";a(m).css("opacity",c.overlayOpacity).fadeIn(c.overlayFadeDuration);s();D(1);h=b;c.loop=c.loop&&1<h.length;return z(g)};a.fn.slimbox=function(b,c,d){c=c||function(a){return[a.href,a.title]};d=d||function(){return!0};var g=this;return g.unbind("click").click(function(){var s=this,h=0,f,e=0,k;f=a.grep(g,function(a,b){return d.call(s,a,b)});for(k=f.length;e<k;++e)f[e]==s&&(h=e),f[e]=c(f[e],e);return a.slimbox(f,h,b)})}})(jQuery);
/android|iphone|ipod|series60|symbian|windows ce|blackberry/i.test(navigator.userAgent)||jQuery(function(a){a("a[rel^='lightbox']").slimbox({},null,function(a){return this==a||8<this.rel.length&&this.rel==a.rel})});
/android|iphone|ipod|series60|symbian|windows ce|blackberry/i.test(navigator.userAgent)||jQuery(function(a){a("a[href^='http://www.flickr.com/photos/'] > img:first-child[src]").parent().slimbox({},function(a){return[a.firstChild.src.replace(/_[mts]\.(\w+)$/,".$1"),(a.title||a.firstChild.alt)+'<br /><a href="'+a.href+'">Flickr page</a>']})});
//]]>
